
server:
  port: 8080


logging:
  level:
    root: warn

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.4.85:5431/gang
    username: postgres
    password: postgres

    data: classpath*:init.sql
    initialization-mode: always

  jpa:
      hibernate:
        ddl-auto: update

#      naming:                           #解决不认大写字母  这样设置后可以解决，但同样不认驼峰规则了
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

      properties:
        hibernate:
          dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect    #与jts_geometry相关
          temp:
            use_jdbc_metadata_defaults: false
      show-sql: true

swagger:
  enabled: true
  title: 开发文档
  version: ${spring.application.version}
  description: 开发文档
  exclude-path: /error,/actuator/**
  contact:
    name: CoderLG
    email: im.lg@qq.com
  authorization:
    name: 认证头
    key-name: Authorization

number: 2


#  rabbitmq:
#    addresses: 192.168.4.78
#    port: 15672
#    username: guest
#    password: guest


#  rabbitmq:
#    host: ${rabbitmq_host}
#    port: ${rabbitmq_port}
#    username: ${rabbitmq_username}
#    password: ${rabbitmq_password}


