

spring:
  application:
    name: Demo
    version: ${random.long}
  profiles:
    active: dev

swagger:
  enabled: true
  title: 开发文档
  version: ${spring.application.version}
  description: 开发文档
  exclude-path: /error,/actuator/**
  contact:
    name: CoderLG
    email: im.lg@qq.com
  authorization:
    name: 认证头
    key-name: Authorization

number: 2



#ribbon:
#  ReadTimeout: 15000
#  ConnectTimeout: 15000
#  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
#  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
#  OkToRetryOnAllOperations: false  #是否所有操作都重试
#
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://192.168.4.47:28761/eureka/


